### ISSUE TITLE
Update orderbook automatically

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1040]
It would be nice to be able to have a live version of the order book.

Probably once the event base order book @fleupold  and @nlordell is live, there's possible more options to implement a live order book. An ideal outcome would be to have a websocket notifying either the deltas or the full-updates. How feasable would this be?

For now, the front-end could take a simple approach of re-fetching the data automatically every 30s or so.

@alfetopito @Velenir what do you think?

**Comment by Velenir** [comment]
Add `blockNumber` dep to hook?
Add `blockNumber` dep to hook

**Comment by anxolin** [comment]
The orderbook changes not on every batch, but on every order/deposit/withdrawal/solution 
Right now is a bit costly for the service, this is why I didn't want a big frequency

2 users querying the same order book (base/quote/hops) could return the same result. So it's highly cacheable at both HTTP and SERVICE level. I mean, both an internal cache and using `cache-control` in the backend headers could instruct the browser and any intermediate server about the caching policy.

With that we can do queries more often without punishing the server.

The next step could be evaluate if we can use Web Sockets, so the server pushes every time he recalculates the order book, or if at some point we want to implement one super efficient, we try to push just the deltas (price points that change)

**Comment by alfetopito** [comment]
> For now, the front-end could take a simple approach of re-fetching the data automatically every 30s or so.

Dumb and quick idea: cache the call response on the frontend for ~30s. Update the orderbook component every ~5 seconds.

**Comment by nlordell** [comment]
> Probably once the event base order book is live

It should be currently live.

Is issue specifically for the transient orderbook (showing the fancy graph for overlapping orders between two tokens)?

**Comment by anxolin** [comment]
> Dumb and quick idea: cache the call response on the frontend for ~30s. Update the orderbook component every ~5 seconds.

👌something like that is already a great start. It was kind of my suggestion. 
I was also making reference on where we could add the caches. If they for example update every 5s they can return the cache control for 1s (or even for the time to the next update). Then any request done to their service, wouldn't arrive even to the node code, because nginx can eat that up.

> Is issue specifically for the transient orderbook (showing the fancy graph for overlapping orders between two tokens)?

Yes. Someone asked us if we need to REFRESH to see the changes in the order book. Normally people is use to getting automatic refresh in the data for that.

![image](https://user-images.githubusercontent.com/2352112/82694915-65fd8e80-9c64-11ea-8146-ff81fb919a1e.png)

> It should be currently live.

I understood that that's for the price, but not for the order book: https://dex-price-estimator.gnosis.io/api/v1/markets/7-4?atoms=true&hops=2

That part is still a bit slow, and it looks that it doesn't have any cache judging from the response headers and the time of execution of two consecutive orders.

That's why I think it could be a good idea to implement those.

**Comment by nlordell** [comment]
> Then any request done to their service, wouldn't arrive even to the node code, because nginx can eat that up.

Thats a very good idea!

> I understood that that's for the price, but not for the order book [...] That part is still a bit slow

AFAIK, currently both the orderbook and the price estimation routes use the event-based orderbook. The issue with the transient orderbook calculation is that it currently takes up a good chunk of time (order of ~10s). We have discussed using a similar approach to price estimation using `pricegraph` + Wasm for calculating transient orderbooks, but this is slightly more complicated than price estimation and we haven't entirely figured out how it will work.

> cache judging from the response headers and the time of execution of two consecutive orders.

As far as I know it doesn't. This is a very good idea and an quick improvement that we can make to the price estimator for now.

**Comment by fleupold** [comment]
I'm not sure how much value a server-side cache outside of the business logic will have. Please prove me wrong, but I think we are currently not experiencing many concurrent users of our system (therefore requests for the same token pair are likely going to come from the same client).

I agree with the proposal that caching the orderbook on the server and only invalidating it when a new material event arrives might help.

**Comment by anxolin** [comment]
> Please prove me wrong, but I think we are currently not experiencing many concurrent users of our system (therefore requests for the same token pair are likely going to come from the same client).

Not sure I understand. If we add auto refresh, 2 uses seeing the orderbook will be making requests that could use this cache. 
I think for something so costly and with so little parameters, a cache seems like a good fit

**Comment by fleupold** [comment]
Yes, my claim is we don't very often have more than one user use our system at the same time and given that a business logic agnostic cache is tricky to invalidate (the only way I'm aware of is by ttl  and block times are non-deterministic), I'm not sure it's actually worth doing this.

**Comment by nlordell** [comment]
> the only way I'm aware of is by ttl and block times are non-deterministic

But our update interval is deterministic, which means we know exactly when `/api/v1/markets/foo-bar` will be invalidated, that is it will only be valid for the time remaining until the next update.

**Comment by fleupold** [comment]
Ah right, we are polling new events and not subscribing to them. In that case there is no need to cache inside the business logic.

**Comment by alfetopito** [comment]
_Estimation: 1.5_

Also, add loading indicator.

**Comment by alfetopito** [comment]
1 liner: https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Updating_existing_data

**Comment by Velenir** [comment]
*Estimation: 0.5*

**Comment by alfetopito** [comment]
Moved to `gp-ui`. See https://github.com/gnosis/gp-ui/pull/7
