### ISSUE TITLE
Order Book: Linear price for the X-axis

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1049]
![image](https://user-images.githubusercontent.com/2352112/82791977-f1e30680-9e6e-11ea-9667-10bc1f8ff14e.png)

https://gnosisinc.slack.com/archives/CSGLUC1BN/p1590145766002600

> This view suggest that there is a big spread between buy and sell. In reality it is not, it is many very small orders (on the red side) with almost the same price. However - the scale of the x axis is not linear

**Comment by Velenir** [comment]
_Estimation: 3_

**Comment by alfetopito** [comment]
Moved to `gp-ui`. See https://github.com/gnosis/gp-ui/pull/6
