### ISSUE TITLE
Order Book: Table View

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1050]
Feedback from one of the power users.

> also the visual orderbook view is good but it is also good to have just a table with orders where I can read the levels
> I would say that is more fundamental

**Comment by besoeasy** [comment]
yes general orderbook would be nice

**Comment by alfetopito** [comment]
_Estimation: 2_

Create a mock proposal. Share proposal on DAOTalk.

**Comment by anxolin** [comment]
bad bot

**Comment by alfetopito** [comment]
This is part of the `gp-v1-ui-v2` AKA `expert trader UI` and won't be added to `dex-react` AKA `gp-v1` AKA `mesa`.

Closing
