### ISSUE TITLE
Remove "Do you want to add new Tokens?"

### ISSUE THREAD

**Issue by ghost** [gnosis/gp-v1-ui#1106]
This project is great when used in iframe on website as widget but **Do you want to add new Tokens?** breaks things, allow token addition if given by url

https://github.com/gnosis/dex-react/blob/2b675265dbfb4eb1726f934152ac740936463067/src/hooks/useBetterAddTokenModal.tsx#L247

**Comment by alfetopito** [comment]
The referred app is going into read only mode.
This is a won't fix.

A new repo (forked from this) https://github.com/gnosis/gp-ui  will continue the development of related apps, but not the formed `dex-react`
