### ISSUE TITLE
Issue when there's 2 tokens with the same symbol

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1194]
Use an unique identifier for the token, such us token id or address to prevent this situations.

See thread: 
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1593945545064400

At least affects:
* The drop down selector for tokens
* The balance
* the balance indicator

cc/ @bh2smith

**Comment by alfetopito** [comment]
_Estimation: 2_

**Comment by anxolin** [comment]
bad bot

**Comment by alfetopito** [comment]
Won't fix.

We'll keep that in mind for the next versions though ;)
