### ISSUE TITLE
Include fee in orderbook prices

### ISSUE THREAD

**Issue by Rafanator** [gnosis/gp-v1-ui#1300]
Again from Crypcat, he commented:

`it should be quite clear at which price my order gets into the order book.
if i set the price @380, it's quite unacceptable to see it @379.7 on the book.
Especially when each orderbook action is a tx.`

It is important for us to note the following:

1. The price estimator needs to include the fee or else the trade won't be matched 
2. The price estimator and the orderbook don't match 
3. No other exchange shows the fee in the orderbook

I had a brief conversation about this with Martin, and we thought that it makes more sense to include the fee in the orderbook in order to confuse the users. 

@anxolin Mentioned that it is tricky to include the fee when ring trades are involved. 

What should we do?

**Comment by anxolin** [comment]
bad bot

**Comment by alfetopito** [comment]
Won't fix.

We should though keep this in mind when working on the trade UI/batch explorer
