### ISSUE TITLE
Guided tour of the App

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1343]
Some users have expressed that the first time in Mesa is not super straight forward, then, once you know your way around is better.

Some users expressed that they would like a guided tour that would show the distinct parts of the app.

I don't want to put excessive effort in this, since we will be changing the UI iteratively and it probably will need some maintenance, but I still think it's worth to do a guided tour.

## Possible steps
* [ ] Review libraries that allow this
* [ ] get inspiration from those libraries and what other exchanges do. @Rafanator already started a document for this
* [ ] Discuss in a doc the steps we want to define, and it's content
* [ ] Validate with stakeholders
* [ ] Do it 🚀

## Some demos
* https://react-joyride.com/
* https://reactour.js.org/

## Nice read
* https://blog.logrocket.com/complete-guide-to-build-product-tours-on-your-react-apps/
* https://www.smashingmagazine.com/2020/08/guide-product-tours-react-apps/

cc/ @Rafanator, @biocom

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/12
