### ISSUE TITLE
Show orderbook next to the LimitOrder widget

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1393]
https://github.com/gnosis/dex-react/pull/1353

![image](https://user-images.githubusercontent.com/2352112/92745099-583e5700-f382-11ea-8746-2a096cdc87f1.png)

First small UI redisign
* Gain extra space
* Show order book next to the limit order form

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/11
