### ISSUE TITLE
TheGraph integration tasks

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1414]
The Graph API:
https://thegraph.com/explorer/subgraph/gnosis/protocol-xdai
https://thegraph.com/explorer/subgraph/gnosis/protocol-rinkeby
https://thegraph.com/explorer/subgraph/gnosis/protocol

Some initial PR: Add apollo + Last Trades
#1406

Some other **Pending Tasks** to research/implement:
* [ ] Add better support for typescript: Autogenerate?
* [ ] Add better parametrization of the widget
* [ ] Pagination?
* [ ] Subscriptions: Update automatically (change https for WS)
* [ ] Review if we want to implement more fined cache strategies

**Comment by anxolin** [comment]
bad bot

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/14
