### ISSUE TITLE
[Orderbook] Detect price reference

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1481]
For some calculations in the orderbook, we need to calculate a price reference.

The final goal is to leave some outlier prices out of the chart, since representing too expensive prices can make the graph not informative.

## Price Reference to filter outliers
We could find a **Price Reference (PR)**, and use this price to decide what is too expensive prices.
One proposal would be, let's not represent any price that is:
  * Smaller than `PR / RELEVANT_PRICE_FACTOR`
  * Greater than  `PR * RELEVANT_PRICE_FACTOR` 

Where `RELEVANT_PRICE_FACTOR`, is a constant. We could start with 2.5 as the value and evaluate with different data examples.

This idea could be reiterated, and make a smarter selection of the `RELEVANT_PRICE_FACTOR`, where it can be closer to 1 if it's a super liquid market, and it's closer to 10 if it's illiquid.
* To measure how liquid it is, we can measure how much volume we have around the **Price Reference**
* For example, we could go in small increments of price factor, until we include/represent a % of all available volume, or minimum volume of $100K (for example)

## How to calculate the Price reference
One trivial implementation could be:
* Let's get the best ask, and best bid, and calculate the middle point
* `PR =  ABS(BA  + BB) / 2`
* This would work in the case where there's a spread,  and where is not.

One issue with the previous implementation, is that a tiny tiny buy or sell order, with a price close to 0, would break the calculation.
This implementation may be good enough if we discard market orders that don't have a minimum liquidity. 

We can design extreme test case, and validate if this approach is enough. If it's not, we could reiterate on this, and instead of using the Best Ask and Best Bid, we would use the **The price we would get for buying/selling VOLUME_FOR_PRICE_REFERENCE**

So, we could have a `VOLUME_FOR_PRICE_REFERENCE_USD` constant (for example $1000), and calculate the price where we can buy and sell that volume. This will be likely a more realistic price.

Graphically:
![image](https://user-images.githubusercontent.com/2352112/95062014-abdf5e80-06fc-11eb-82a3-058b62b2e057.png)

## PR can be used for centering the chart in that price
* We would draw a vertical line in that price
* We center in that price
* When we zoom in, we keep that price in the center always. We only change the minimun/maximun represented price

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/11
