### ISSUE TITLE
[Orderbook] Fee coherence

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1484]
This issue is for now on hold, but it should become relevant

There's a coherence issue regarding the submitted order 

There's a WIP document that was created to define the issue and discuss the solutions:
https://docs.google.com/document/d/1Rdn3qGMGBA0J6iBaPLNXzMA3NbQjbs_6L4i-4Zsv1JM/edit#heading=h.70zaok7ufpf7

In summary, I believe we shouldn't hide the fee to the user, since this creates an incoherence between the order he creates and the one he sees in the orderbook. Also because, in order to match an order from that he is visually seeing in the orderbook, he needs to calculate the price applying the fee.

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/11
