### ISSUE TITLE
Rinkeby Network not working for Metamasks IOS 

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1617]
![image](https://user-images.githubusercontent.com/2352112/99060438-51111080-25a0-11eb-9f88-e4b1735e27b2.png)

It doesn't recognize the network, and the app cannot be used in Metamask IOS version connected to Rinkeby.

If I change the network, back and forth, it works though

**Comment by alfetopito** [comment]
Could it be a temporary issue with metamask?
What browser and MM version?
Still reproduce-able?

Re-open if you still do see it.

This is a won't fix, but we might need to revisit for other apps
