### ISSUE TITLE
MM Mobile doesn't use 1GWEI gas price on xDAI

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v1-ui#1649]
Probably not worthwhile fixing, but just wanted to document that when using Mesa with Metamask on iOS on xDAI all transactions are priced using the current mainnet gas estimate (on Desktop we successfully override the gas price with 1GWEI).

Might be a metamask issue as well.

**Comment by alfetopito** [comment]
I believe this is an issue with MM and xDai, as I've seen the same reported by Safe users.
